//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apartmani
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Apartmani()
        {
            this.Rezervacije = new HashSet<Rezervacije>();
        }
    
        public int Id_apartmana { get; set; }
        public string Adresa { get; set; }
        public int Broj_soba { get; set; }
        public string Pogled_na_more { get; set; }
        public string Perilica { get; set; }
        public string Terasa { get; set; }
        public decimal Cijena_noć { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezervacije> Rezervacije { get; set; }
    }
}
