//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HotelBazaEntities11 : DbContext
    {
        public HotelBazaEntities11()
            : base("name=HotelBazaEntities11")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Apartmani> Apartmani { get; set; }
        public virtual DbSet<Drzava> Drzava { get; set; }
        public virtual DbSet<Gost> Gost { get; set; }
        public virtual DbSet<Grad> Grad { get; set; }
        public virtual DbSet<Hotel> Hotel { get; set; }
        public virtual DbSet<Korisnik> Korisnik { get; set; }
        public virtual DbSet<Nacin_placanja> Nacin_placanja { get; set; }
        public virtual DbSet<PlanRada> PlanRada { get; set; }
        public virtual DbSet<Popusti> Popusti { get; set; }
        public virtual DbSet<Racun> Racun { get; set; }
        public virtual DbSet<RadnoVrijeme> RadnoVrijeme { get; set; }
        public virtual DbSet<Rezervacije> Rezervacije { get; set; }
        public virtual DbSet<Soba> Soba { get; set; }
        public virtual DbSet<Ugovaranje_putem> Ugovaranje_putem { get; set; }
        public virtual DbSet<Uloge> Uloge { get; set; }
        public virtual DbSet<Zaposlenik> Zaposlenik { get; set; }
    }
}
