//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanRada
    {
        public int Id_plan_rada { get; set; }
        public int Id_radno_vrijeme { get; set; }
        public int Id_zaposlenika { get; set; }
        public System.DateTime Datum { get; set; }
    
        public virtual Zaposlenik Zaposlenik { get; set; }
        public virtual RadnoVrijeme RadnoVrijeme { get; set; }
    }
}
