//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Racun
    {
        public int Id_racuna { get; set; }
        public Nullable<decimal> Ukupan_trošak { get; set; }
        public Nullable<int> Id_popust { get; set; }
        public int Id_zaposlenika { get; set; }
        public System.DateTime Datum_plačanja { get; set; }
        public int Id_rezervacije { get; set; }
        public int Id_nacin_placanja { get; set; }
    
        public virtual Nacin_placanja Nacin_placanja { get; set; }
        public virtual Popusti Popusti { get; set; }
        public virtual Rezervacije Rezervacije { get; set; }
        public virtual Zaposlenik Zaposlenik { get; set; }
    }
}
