//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezervacije
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rezervacije()
        {
            this.Racun = new HashSet<Racun>();
        }
    
        public int Id_rezervacija { get; set; }
        public Nullable<int> Id_soba { get; set; }
        public Nullable<int> Id_apartman { get; set; }
        public int Id_gosta { get; set; }
        public System.DateTime Datum_check_in { get; set; }
        public System.DateTime Datum_check_out { get; set; }
        public int Id_ugovaranje_putem { get; set; }
    
        public virtual Apartmani Apartmani { get; set; }
        public virtual Gost Gost { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Racun> Racun { get; set; }
        public virtual Soba Soba { get; set; }
        public virtual Ugovaranje_putem Ugovaranje_putem { get; set; }
    }
}
