//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Soba
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Soba()
        {
            this.Rezervacije = new HashSet<Rezervacije>();
        }
    
        public int Id_sobe { get; set; }
        public short Broj_kreveta { get; set; }
        public string Terasa { get; set; }
        public string Pogled_na_more { get; set; }
        public string Lift { get; set; }
        public string Perilica { get; set; }
        public decimal Cijena_noć { get; set; }
        public short Broj_sobe { get; set; }
        public int Id_hotel { get; set; }
    
        public virtual Hotel Hotel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezervacije> Rezervacije { get; set; }
    }
}
